#! /bin/env python
#
# Michael Gibson 17 July 2015
# Modified Adrian Foy January 2023
import re
import math, os, time
import mne
import numpy as np
import json

from intanutil.read_header import read_header
from intanutil.get_bytes_per_data_block import get_bytes_per_data_block
from intanutil.read_one_data_block import read_one_data_block
from intanutil.notch_filter import notch_filter
from intanutil.data_to_result import data_to_result
import pickle
from collections import Counter
import matplotlib.pyplot as plt


def read_data(filename):
    """Reads Intan Technologies RHD2000 data file generated by evaluation board GUI.

    Data are returned in a dictionary, for future extensibility.
    """

    tic = time.time()
    fid = open(filename, 'rb')
    filesize = os.path.getsize(filename)

    header = read_header(fid)

    # Determine how many samples the data file contains.
    bytes_per_block = get_bytes_per_data_block(header)

    # How many data blocks remain in this file?
    data_present = False
    bytes_remaining = filesize - fid.tell()
    if bytes_remaining > 0:
        data_present = True

    num_data_blocks = int(bytes_remaining / bytes_per_block)
    print('num_data_blocks:', num_data_blocks)
    print('bytes_remaining:', bytes_remaining)
    print('bytes_per_block:', bytes_per_block)

    if bytes_remaining % bytes_per_block != 0:
        # raise Exception('Something is wrong with file size : should have a whole number of data blocks')
        print("数据块大小不是整数，读取数据可能存在异常，请检查数据文件是否正常！")
        bytes_remaining = int(bytes_remaining / bytes_per_block) * bytes_per_block

    num_amplifier_samples = header['num_samples_per_data_block'] * num_data_blocks
    num_aux_input_samples = int((header['num_samples_per_data_block'] / 4) * num_data_blocks)
    num_supply_voltage_samples = 1 * num_data_blocks
    num_board_adc_samples = header['num_samples_per_data_block'] * num_data_blocks
    num_board_dig_in_samples = header['num_samples_per_data_block'] * num_data_blocks
    num_board_dig_out_samples = header['num_samples_per_data_block'] * num_data_blocks

    record_time = num_amplifier_samples / header['sample_rate']

    if data_present:
        print('File contains {:0.3f} seconds of data.  Amplifiers were sampled at {:0.2f} kS/s.'.format(record_time,
                                                                                                        header[
                                                                                                            'sample_rate'] / 1000))
    else:
        print('Header file contains no data.  Amplifiers were sampled at {:0.2f} kS/s.'.format(
            header['sample_rate'] / 1000))

    if data_present:
        # Pre-allocate memory for data.
        print('')
        print('Allocating memory for data...')

        data = {}
        if (header['version']['major'] == 1 and header['version']['minor'] >= 2) or (header['version']['major'] > 1):
            data['t_amplifier'] = np.zeros(num_amplifier_samples, dtype=np.int_)
        else:
            data['t_amplifier'] = np.zeros(num_amplifier_samples, dtype=np.uint)

        data['amplifier_data'] = np.zeros([header['num_amplifier_channels'], num_amplifier_samples], dtype=np.uint)
        data['aux_input_data'] = np.zeros([header['num_aux_input_channels'], num_aux_input_samples], dtype=np.uint)
        data['supply_voltage_data'] = np.zeros([header['num_supply_voltage_channels'], num_supply_voltage_samples],
                                               dtype=np.uint)
        data['temp_sensor_data'] = np.zeros([header['num_temp_sensor_channels'], num_supply_voltage_samples],
                                            dtype=np.uint)
        data['board_adc_data'] = np.zeros([header['num_board_adc_channels'], num_board_adc_samples], dtype=np.uint)

        # by default, this script interprets digital events (digital inputs and outputs) as booleans
        # if unsigned int values are preferred(0 for False, 1 for True), replace the 'dtype=np.bool_' argument with 'dtype=np.uint' as shown
        # the commented line below illustrates this for digital input data; the same can be done for digital out

        # data['board_dig_in_data'] = np.zeros([header['num_board_dig_in_channels'], num_board_dig_in_samples], dtype=np.uint)
        data['board_dig_in_data'] = np.zeros([header['num_board_dig_in_channels'], num_board_dig_in_samples],
                                             dtype=np.bool_)
        data['board_dig_in_raw'] = np.zeros(num_board_dig_in_samples, dtype=np.uint)

        data['board_dig_out_data'] = np.zeros([header['num_board_dig_out_channels'], num_board_dig_out_samples],
                                              dtype=np.bool_)
        data['board_dig_out_raw'] = np.zeros(num_board_dig_out_samples, dtype=np.uint)

        # Read sampled data from file.
        print('Reading data from file...')

        # Initialize indices used in looping
        indices = {}
        indices['amplifier'] = 0
        indices['aux_input'] = 0
        indices['supply_voltage'] = 0
        indices['board_adc'] = 0
        indices['board_dig_in'] = 0
        indices['board_dig_out'] = 0

        print_increment = 10
        percent_done = print_increment
        for i in range(num_data_blocks):
            read_one_data_block(data, header, indices, fid)

            # Increment indices
            indices['amplifier'] += header['num_samples_per_data_block']
            indices['aux_input'] += int(header['num_samples_per_data_block'] / 4)
            indices['supply_voltage'] += 1
            indices['board_adc'] += header['num_samples_per_data_block']
            indices['board_dig_in'] += header['num_samples_per_data_block']
            indices['board_dig_out'] += header['num_samples_per_data_block']

            fraction_done = 100 * (1.0 * i / num_data_blocks)
            if fraction_done >= percent_done:
                # print('{}% done...'.format(percent_done))
                percent_done = percent_done + print_increment

        # Make sure we have read exactly the right amount of data.
        bytes_remaining = filesize - fid.tell()
        if bytes_remaining != 0:
            # raise Exception('Error: End of file not reached.')
            print("数据块大小不匹配，读取数据可能存在异常，请检查数据文件是否正常!")

    # Close data file.
    fid.close()

    if data_present:
        print('Parsing data...')

        # Extract digital input channels to separate variables.
        for i in range(header['num_board_dig_in_channels']):
            data['board_dig_in_data'][i, :] = np.not_equal(
                np.bitwise_and(data['board_dig_in_raw'], (1 << header['board_dig_in_channels'][i]['native_order'])), 0)

        # Extract digital output channels to separate variables.
        for i in range(header['num_board_dig_out_channels']):
            data['board_dig_out_data'][i, :] = np.not_equal(
                np.bitwise_and(data['board_dig_out_raw'], (1 << header['board_dig_out_channels'][i]['native_order'])),
                0)

        # Scale voltage levels appropriately.
        data['amplifier_data'] = np.multiply(0.195,
                                             (data['amplifier_data'].astype(np.int32) - 32768))  # units = microvolts
        data['aux_input_data'] = np.multiply(37.4e-6, data['aux_input_data'])  # units = volts
        data['supply_voltage_data'] = np.multiply(74.8e-6, data['supply_voltage_data'])  # units = volts
        if header['eval_board_mode'] == 1:
            data['board_adc_data'] = np.multiply(152.59e-6,
                                                 (data['board_adc_data'].astype(np.int32) - 32768))  # units = volts
        elif header['eval_board_mode'] == 13:
            data['board_adc_data'] = np.multiply(312.5e-6,
                                                 (data['board_adc_data'].astype(np.int32) - 32768))  # units = volts
        else:
            data['board_adc_data'] = np.multiply(50.354e-6, data['board_adc_data'])  # units = volts
        data['temp_sensor_data'] = np.multiply(0.01, data['temp_sensor_data'])  # units = deg C

        # Check for gaps in timestamps.
        num_gaps = np.sum(np.not_equal(data['t_amplifier'][1:] - data['t_amplifier'][:-1], 1))
        if num_gaps == 0:
            print('No missing timestamps in data.')
        else:
            print('Warning: {0} gaps in timestamp data found.  Time scale will not be uniform!'.format(num_gaps))

        # Scale time steps (units = seconds).
        data['t_amplifier'] = data['t_amplifier'] / header['sample_rate']
        data['t_aux_input'] = data['t_amplifier'][range(0, len(data['t_amplifier']), 4)]
        data['t_supply_voltage'] = data['t_amplifier'][
            range(0, len(data['t_amplifier']), header['num_samples_per_data_block'])]
        data['t_board_adc'] = data['t_amplifier']
        data['t_dig'] = data['t_amplifier']
        data['t_temp_sensor'] = data['t_supply_voltage']

        # If the software notch filter was selected during the recording, apply the
        # same notch filter to amplifier data here.
        if header['notch_filter_frequency'] > 0 and header['version']['major'] < 3:
            print('Applying notch filter...')

            print_increment = 10
            percent_done = print_increment
            for i in range(header['num_amplifier_channels']):
                data['amplifier_data'][i, :] = notch_filter(data['amplifier_data'][i, :], header['sample_rate'],
                                                            header['notch_filter_frequency'], 10)

                fraction_done = 100 * (i / header['num_amplifier_channels'])
                if fraction_done >= percent_done:
                    # print('{}% done...'.format(percent_done))
                    percent_done += print_increment
    else:
        data = []

    # Move variables to result struct.
    result = data_to_result(header, data, data_present)

    print('Done!  Elapsed time: {0:0.1f} seconds'.format(time.time() - tic))
    return result


def rhd_to_raw(path):
    a = read_data(path)
    print(a.keys())
    # end_point = min(end_point, a['amplifier_data'].shape[1])

    amplifier_data = a['amplifier_data']
    chans = a['amplifier_channels']
    channel_name = []
    # 把原本的A-000电极名称处理成了0 纯数字，方便之后对应电极关系图
    for chan in chans:
        channel_name.append(str(int(chan['custom_channel_name'].split('-')[-1])))

    sfreq = a['frequency_parameters']['amplifier_sample_rate']

    info = mne.create_info(channel_name, sfreq, ch_types='ecog', verbose=None)
    raw = mne.io.RawArray(amplifier_data, info)
    times = a['t_amplifier']
    # raw._data *= 1e-6

    return raw, times


def find_all_subsequences(seq, sub_seq):
    idx = 0
    for i in range(len(seq) - len(sub_seq) + 1):
        if seq[i] == 1:
            idx += 1
        if (seq[i:i + len(sub_seq)] == np.array(sub_seq)).all():
            yield i, idx


def read_statereader(statereader_path):
    with open(statereader_path, 'r', encoding='utf-8') as f:
        log_lines = f.readlines()
    # 仅保存有pos的line
    pos_lines = []
    for line in log_lines:
        if "ball_pos" in line:
            pos_lines.append(line)

    labels = []
    trial_num = []
    pos = []

    # 定义正则表达式模式
    pattern_real = r"target=\[(\d)+\]"
    pattern_trialnum = r'trial_number=(\d+)'  # 提取 trialnum 的数字部分
    pattern_pos = r'ball_pos=(.*)'

    for line in pos_lines:
        text = line.strip()
        try:
            real = int(re.search(pattern_real, text).group(1))
            labels.append(real)

            trialnum = int(re.search(pattern_trialnum, text).group(1))
            trial_num.append(trialnum)
        except:
            pass
        ball_pos = re.search(pattern_pos, text).group(1)
        ball_pos_list = [float(value.strip()) for value in ball_pos.strip('[]').split(',')]
        pos.append(ball_pos_list)

    # split trail using trial_num
    trail_pos = []
    trail_labels = []
    try:
        num_trails = len(set(trial_num))
        for i in range(num_trails):
            indices = [j for j, x in enumerate(trial_num) if x == i]
            if len(indices) > 0:
                trail_pos.append([pos[j] for j in indices])
                trail_labels.append(labels[indices[0]])  # Assuming the label is the same for all indices in a trial
    except:
        pass

    return trial_num, trail_pos, trail_labels, pos


def hunman_center_out(data_path, marker_path, sfreq=600, shift=None, save_root=None, log=None):
    marker_id = json.load(open('marker.json', 'r'))
    mi_id = marker_id['human_center_out']

    success_tar_list = [mi_id['go_signal'], mi_id['target_hold'], mi_id['rest_start'], mi_id['end_trial']]
    failure_tar_list = [mi_id['go_signal'], mi_id['center_on']]

    if shift is None:
        shift = sfreq

    raw, times = rhd_to_raw(data_path)

    event_data = []
    with open(marker_path, "r+", encoding='utf-8') as file:
        for line in file:
            # 按逗号分割每一行并提取第一列和第三列
            try:
                parts = line.strip().split(",")
                if len(parts) >= 3:
                    first_col = int(parts[0].strip())
                    if first_col > 0:
                        marker, label = parts[2].strip().split('_')
                        marker = int(marker)
                        label = int(label)
                        event_data.append([first_col, marker, label])
            except:
                continue


    event_data = np.array(event_data)
    print('event_data:', event_data.shape)

    success_trial_idx = np.array(list(find_all_subsequences(event_data[:, 1], success_tar_list)))
    failure_trial_idx = np.array(list(find_all_subsequences(event_data[:, 1], failure_tar_list)))
    if len(success_trial_idx) != 0:
        success_trial_idx, success_trial_pos = success_trial_idx[:, 0], success_trial_idx[:, 1]
    if len(failure_trial_idx) != 0:
        failure_trial_idx, failure_trial_pos = failure_trial_idx[:, 0], failure_trial_idx[:, 1]
    num_trails = len(success_trial_idx) + len(failure_trial_idx)
    data = raw.get_data()

    pos = None
    if log is not None:
        trial_num, trail_pos, trail_labels, pos = read_statereader(log)
        if len(trail_pos) == 0:
            pos = np.array(pos)
            pos = pos.reshape(num_trails, -1, 2)
        else:
            pos = trail_pos
        # pos = pos[success_trial_pos]

    trial_data = []
    trial_rest_data = []
    labels = []

    for i in range(len(success_trial_idx)):
        label = event_data[success_trial_idx[i]][-1]
        go_signal = event_data[success_trial_idx[i]][0]
        target_hold = event_data[success_trial_idx[i] + 1][0]
        rest = event_data[success_trial_idx[i] + 2][0]
        end = event_data[success_trial_idx[i] + 3][0]

        # 简化数组索引
        try:
            temp = data[:, go_signal:target_hold]
            test_data = data[:, rest:end]
            trial_rest_data.append(test_data)
            trial_data.append(temp)
            labels.append(label)
        except IndexError:
            print(f"索引超出范围，跳过trial {i}")
            continue

    for i in range(len(failure_trial_idx)):
        label = event_data[failure_trial_idx[i]][-1]
        go_signal = event_data[failure_trial_idx[i]][0]

        # 简化数组索引
        try:
            temp = data[:, go_signal:go_signal + 4 * sfreq]
            trial_data.append(temp)
            trial_rest_data.append(None)
            labels.append(label)
        except IndexError:
            print(f"索引超出范围，跳过失败trial {i}")
            continue

    labels = np.array(labels)

    count = len(Counter(labels))
    rest_labels = np.array([count] * len(trial_rest_data))
    z = Counter(labels)
    print('center_out_to_mat:', {int(key): value for key, value in z.items()})
    success_failure = [True] * len(success_trial_idx) + [False] * len(failure_trial_idx)

    return trial_data, labels, pos, trial_rest_data, rest_labels, success_failure


if __name__ == '__main__':
    # pos = 'tiantan/S01'
    pos = 'beida'
    root = f'/mnt/ata-aigo_SSD/Dataset/{pos}/raw'
    date = [
        # '20250304',
        # '20250305',
        # '20250308',
        # '20250309_am',
        # '20250310_am',
        # '20250309_pm',
        # '20250310_pm',
        # '20250311',
        # '20250312',
        # '20250314',
        # '20250317',
        # '20250318',
        # '20250319',
        # '20250320',
        # '20250321',
        # '20250323',
        # '20250324',
        # '20250325',
        # '20250326',
        # '20250327',
        # '20250401',
        # '20250402'
        # '20250403'
        # '20250411',
        # '20250414',
        # '20250415',
        # '20250416',
        # '20250418',
        # '20250419',
        # '20250428'
        # '20250430',
        # '20250422_0423_0427_left_feet',
        # '20250428_0429_0430_right_elbow',
        # '20250506',
        # '20250507',
        # '20250508',
        # '20250427',
        # '20250428',
        # '20250429',
        # '20250430',
        # '20250506',
        # '20250507',
        # '20250508',
        # '20250509',
        # '20250513',
        # '20250514',
        # '20250515',
        # '20250516',
        # '20250520',
        # '20250521',
        # '20250522',
        # '20250523',
        # '20250526',
        # '20250527',
        # '20250528',
        # '20250529',
        # '20250530',
        # '20250603',
        # '20250604',
        # '20250605',
        # '20250606',
        # '20250609',
        # '20250610',
        '20250611',
        '20250612',
        '20250613',
        '20250616',
        '20250617',
    ]
    file_path = [os.path.join(root, d, i) for d in date for i in os.listdir(os.path.join(root, d))]

    for path in file_path:
        rhd = [i for i in os.listdir(path) if i.endswith('.rhd')]
        if len(rhd) == 0:
            continue
        rhd = rhd[0]
        notes = os.path.join(path, 'notes.txt')

        log = [os.path.join(path, i) for i in os.listdir(path) if i.endswith('.log')]
        log = log[0] if len(log) > 0 else None
        save_root = os.path.split(path)[0]
        save_root = save_root.replace('raw', 'daily')
        os.makedirs(save_root, exist_ok=True)
        try:
            hunman_center_out(os.path.join(path, rhd), notes, save_root=os.path.join(save_root, rhd), log=log)
        except Exception as e:
            print('Error:', e)
